//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class AccountMovement : EntityBase
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int AccountID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int OperationTypeID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Client Client { get; set; }
        public virtual OperationType OperationType { get; set; }
    }
}
