//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankDBv2Entities : DbContext
    {
        public BankDBv2Entities()
            : base("name=BankDBv2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountMovement> AccountMovements { get; set; }
        public DbSet<AccountType> AccountTypes { get; set; }
        public DbSet<BankOffice> BankOffices { get; set; }
        public DbSet<Client2Operator> Client2Operator { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CurrenciesExchangeRate> CurrenciesExchangeRates { get; set; }
        public DbSet<OperationType> OperationTypes { get; set; }
        public DbSet<Operator> Operators { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
