//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class BankOffice : EntityBase
    {
        public BankOffice()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string SWIFT { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
