//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Client2Operator : EntityBase
    {
        public int ClientID { get; set; }
        public int OperatorID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool NewStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Operator Operator { get; set; }
    }
}
