//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Currency : EntityBase
    {
        public Currency()
        {
            this.Accounts = new HashSet<Account>();
            this.CurrenciesExchangeRates = new HashSet<CurrenciesExchangeRate>();
            this.CurrenciesExchangeRates1 = new HashSet<CurrenciesExchangeRate>();
        }
    
        public int ID { get; set; }
        public string ISOCode { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<CurrenciesExchangeRate> CurrenciesExchangeRates { get; set; }
        public virtual ICollection<CurrenciesExchangeRate> CurrenciesExchangeRates1 { get; set; }
    }
}
